### PR TITLE
Allow multiple resource files

### PR DESCRIPTION
**Pull request by stephenmichaelf**
This is in reference to:

#242 Enable importing multiple resource files

I changed resource files to a dictionary for quick access, the key and value are the same (the path).

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
@ericsciple Can you review when you get a chance?

**Comment by ericsciple** [comment]
looks good to me, lets merge it

**Comment by kasubram** [comment]
Lets merge it, We would like to consume this change for update2. We have a library which is consumed by few tasks for which we want to add additional localization resource.

**Comment by stephenmichaelf** [comment]
@kasubram Merge complete.

**Comment by bryanmacfarlane** [comment]
done

**Comment by kasubram** [comment]
thanks folks

**Pull request merged**
