### PR TITLE
Adding error code to distinguish between errors

### PR DESCRIPTION
**Pull request by nigurr**

### CODE REVIEW

**Comment by nigurr** [comment]
* Will discuss with @ericsciple  whether to use "Complete Task command result code or use logissue result code"

**Comment by ericsciple** [comment]
Can you only make the minimum change and not reformat the document? I'm having a hard time figuring out what the actual change is.

**Comment by nigurr** [comment]
@ericsciple sorry. couldn't resist pressing formatting shortcut. 

Changes: 
https://github.com/Microsoft/vsts-task-lib/pull/253/files#diff-f7bc92bcb6131b3321462f4336b98b7bR281
https://github.com/Microsoft/vsts-task-lib/pull/253/files#diff-8d040e410d00a119c5517a408d3a7ec0R41

Exposing `resultcode` for warning/error as `logissue` already supports it.
Adding `resultcode` for complete command. this shouldn't break compat as it's new property

**Comment by nigurr** [comment]
@ericsciple can you approve this? :)

**Comment by ericsciple** [comment]
@bryanmacfarlane @TingluoHuang to review since i'm not involved in the current proposed telemetry direction, and this is different than the initial discussion of a ## command

**Comment by ericsciple** [comment]
also does this require a new agent version? you may need to check agent version before including code in the command. would need to be documented on the function comments.

**Comment by nigurr** [comment]
It doesn't require new agent as it's additional property and will not be parsed in older agents.

**Comment by bryanmacfarlane** [comment]
I don't want to hijack warning and error.   It's not a warning or error.

Whether it's not parsed in older agents or not called (##vso) because you don't have a newer agent, the result is the same - older agents won't send telemetry.

Use a new ##vso command

**Comment by nigurr** [comment]
@bryanmacfarlane addressed the review comments. it uses only complete command error code now.

**Comment by nigurr** [comment]
@bryanmacfarlane can you please approve the pr?

**Comment by nigurr** [comment]
@TingluoHuang Can you please merge the PR?

**Pull request merged**
