### PR TITLE
don't add quotes to path input.

### PR DESCRIPTION
**Pull request by TingluoHuang**

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Looks good

**Comment by bryanmacfarlane** [comment]
I would bump the version

**Comment by TingluoHuang** [comment]
Is the fix already in master?  We don't have releases branch.
What testing was done? Verify tasks that use this method continue works.
Does this fix change the AT/DT contract? No
Does this fix include any database servicing changes? No
Were tests added to cover this to make sure it doesn't regress?  We had a L0 test, but verify the wrong case, I change it to verify the correct scenario.

**Comment by bryanmacfarlane** [comment]
We have release branches in tasks which is the ultimate vehicle of this fix.

**Comment by bryanmacfarlane** [comment]
We should also state the customer problem

**Comment by TingluoHuang** [comment]
I list the customer problem in the Bug.

**Comment by TingluoHuang** [comment]
Bug 506238: vsts-task-lib getPathInput() always return path in quotes when path contain space

**Pull request merged**
